export type SourceType = "Forum" | "Social" | "Directory" | "Blog" | "Q&A" | "Classified";
export type Difficulty = "Easy" | "Medium";

export interface TrafficSource {
    id: string;
    name: string;
    niche: string;
    type: SourceType;
    difficulty: Difficulty;
    traffic: string;
    time: string;
    url: string;
    description: string;
    instructions: string[];
}

export const AUTOPILOT_NICHES = [
    "All",
    "Weight Loss",
    "Make Money Online",
    "Health & Fitness",
    "Tech & Gadgets",
    "Beauty & Skincare",
    "Relationships",
    "Pets",
    "Home & Garden",
] as const;

export const TRAFFIC_SOURCES: TrafficSource[] = [    // Weight Loss
    { id: "wl-1", name: "MyFitnessPal Community", niche: "Weight Loss", type: "Forum", difficulty: "Easy", traffic: "200-500 visitors/month", time: "10 minutes", url: "https://community.myfitnesspal.com", description: "I found this complete weight loss guide with science-backed tips that actually helped me drop pounds: {LINK}", instructions: ["Create a free account on MyFitnessPal", "Go to the Community forums section", "Find threads related to your niche (weight loss tips, diet advice)", "Reply to existing threads with helpful advice and naturally include your link", "Create 2-3 new discussion posts per week sharing useful tips with your link in your profile or post"] },
    { id: "wl-2", name: "SparkPeople Forums", niche: "Weight Loss", type: "Forum", difficulty: "Easy", traffic: "150-400 visitors/month", time: "10 minutes", url: "https://www.sparkpeople.com", description: "Sharing this incredible weight loss resource that completely changed my approach to dieting: {LINK}", instructions: ["Sign up for a free SparkPeople account", "Navigate to the Community Message Boards", "Join weight loss and healthy eating groups", "Share helpful posts and include your page URL in your signature", "Engage with other members' posts to build visibility"] },
    { id: "wl-3", name: "3FatChicks Forum", niche: "Weight Loss", type: "Forum", difficulty: "Easy", traffic: "100-300 visitors/month", time: "8 minutes", url: "https://www.3fatchicks.com/forum", description: "This step-by-step weight loss plan helped me break through my plateau — totally free: {LINK}", instructions: ["Register for a free account", "Browse the diet and weight loss discussion boards", "Reply to threads with genuine advice", "Add your page URL to your forum signature", "Start new threads sharing your weight loss journey or tips"] },
    { id: "wl-4", name: "LoseIt! Reddit Community", niche: "Weight Loss", type: "Social", difficulty: "Easy", traffic: "300-800 visitors/month", time: "5 minutes", url: "https://www.reddit.com/r/loseit", description: "Just found this amazing free guide with proven weight loss strategies that actually deliver results: {LINK}", instructions: ["Create a Reddit account if you don't have one", "Subscribe to r/loseit (3M+ members)", "Share a genuine weight loss story or helpful tip", "Include your link naturally when relevant", "Comment on other posts with helpful advice — never spam"] },
    { id: "wl-5", name: "Weight Loss Directory", niche: "Weight Loss", type: "Directory", difficulty: "Easy", traffic: "50-150 visitors/month", time: "5 minutes", url: "https://www.healthline.com", description: "Complete Weight Loss Guide — Science-backed tips and strategies for sustainable fat loss: {LINK}", instructions: ["Search for health and fitness directories online", "Submit your page URL to free directory listings", "Fill in all fields: title, description, category", "Use keywords related to weight loss in your description", "Submit and wait for approval (usually 1-7 days)"] },
    { id: "wl-6", name: "Quora Weight Loss Topics", niche: "Weight Loss", type: "Q&A", difficulty: "Easy", traffic: "500-2000 visitors/month", time: "10 minutes", url: "https://www.quora.com", description: "Here's a free guide with evidence-based weight loss methods that don't require starving yourself: {LINK}", instructions: ["Create a Quora account with a credible bio", "Search for weight loss related questions", "Write detailed, helpful answers (200+ words)", "Include your page URL naturally as a resource", "Answer 2-3 questions per day for best results"] },
    { id: "wl-7", name: "DietBet Community", niche: "Weight Loss", type: "Social", difficulty: "Easy", traffic: "100-400 visitors/month", time: "8 minutes", url: "https://www.dietbet.com", description: "This free weight loss blueprint helped me stay consistent and finally hit my goal weight: {LINK}", instructions: ["Create a DietBet profile", "Join active weight loss challenges", "Engage in community discussions and share tips", "Add your page URL to your profile bio", "Post motivational updates with your link included naturally"] },
    { id: "wl-8", name: "CalorieCount Forum", niche: "Weight Loss", type: "Forum", difficulty: "Easy", traffic: "80-250 visitors/month", time: "8 minutes", url: "https://www.caloriecount.com", description: "Check out this calorie-smart weight loss guide with practical meal plans that make dieting easy: {LINK}", instructions: ["Register a free account", "Navigate to the community discussion boards", "Share helpful calorie counting tips and meal ideas", "Include your link in relevant discussions", "Stay active with 2-3 posts per week"] },
    { id: "wl-9", name: "FatSecret Community", niche: "Weight Loss", type: "Social", difficulty: "Easy", traffic: "150-500 visitors/month", time: "7 minutes", url: "https://www.fatsecret.com", description: "Discovered this nutrition-focused weight loss system that simplifies everything — highly recommend: {LINK}", instructions: ["Sign up for free at FatSecret", "Join community groups related to weight loss", "Share food logs, recipes, and progress updates", "Include your page link in your profile and relevant posts", "Engage consistently for best traffic results"] },
    { id: "wl-10", name: "Weight Watchers Community", niche: "Weight Loss", type: "Forum", difficulty: "Medium", traffic: "200-600 visitors/month", time: "12 minutes", url: "https://www.weightwatchers.com", description: "Comprehensive guide to sustainable weight loss using portion control and smart eating habits: {LINK}", instructions: ["Create a WW community profile", "Browse the success stories and discussion boards", "Share your own tips and helpful advice", "Link to your page as an additional resource", "Be genuine and helpful — avoid hard selling"] },
    { id: "wl-11", name: "Pinterest Weight Loss Boards", niche: "Weight Loss", type: "Social", difficulty: "Easy", traffic: "500-2000 visitors/month", time: "10 minutes", url: "https://www.pinterest.com", description: "Ultimate Weight Loss Guide — Simple daily habits and meal ideas to burn fat naturally: {LINK}", instructions: ["Create a Pinterest business account", "Create boards: 'Weight Loss Tips', 'Healthy Recipes', 'Fitness Motivation'", "Pin images with helpful weight loss tips", "Link each pin back to your page URL", "Pin 5-10 times per day using free scheduling tools"] },
    { id: "wl-12", name: "Medium Health Publication", niche: "Weight Loss", type: "Blog", difficulty: "Medium", traffic: "300-1500 visitors/month", time: "15 minutes", url: "https://medium.com", description: "I wrote about my weight loss journey and the science-backed strategies that finally worked for me: {LINK}", instructions: ["Create a free Medium account", "Write a 500-800 word article about weight loss tips", "Include your page URL naturally in the article", "Submit to health & fitness publications for more reach", "Publish 1-2 articles per week for ongoing traffic"] },

    // Make Money Online
    { id: "mmo-1", name: "Warrior Forum", niche: "Make Money Online", type: "Forum", difficulty: "Easy", traffic: "300-800 visitors/month", time: "10 minutes", url: "https://www.warriorforum.com", description: "Free guide reveals the exact steps I used to build a profitable online income from scratch: {LINK}", instructions: ["Create a free Warrior Forum account", "Set up your forum signature with your page URL", "Browse the main discussion boards", "Reply to threads with genuinely helpful advice", "Start 1-2 new threads per week sharing value"] },
    { id: "mmo-2", name: "BlackHatWorld Forum", niche: "Make Money Online", type: "Forum", difficulty: "Easy", traffic: "200-600 visitors/month", time: "10 minutes", url: "https://www.blackhatworld.com", description: "Here's a proven method for generating passive income online — step-by-step blueprint inside: {LINK}", instructions: ["Register for a free account", "Add your page URL to your signature", "Browse 'Making Money' and 'Affiliate Marketing' sections", "Contribute helpful responses to existing threads", "Avoid spammy posting — focus on adding real value"] },
    { id: "mmo-3", name: "r/WorkOnline Reddit", niche: "Make Money Online", type: "Social", difficulty: "Easy", traffic: "400-1200 visitors/month", time: "5 minutes", url: "https://www.reddit.com/r/WorkOnline", description: "This free guide shows how to start earning real money online without any upfront investment: {LINK}", instructions: ["Join r/WorkOnline on Reddit", "Share a genuine income story or helpful guide", "Include your link as a resource, not an ad", "Comment on other posts with useful tips", "Follow subreddit rules carefully to avoid bans"] },
    { id: "mmo-4", name: "Digital Point Forums", niche: "Make Money Online", type: "Forum", difficulty: "Easy", traffic: "150-500 visitors/month", time: "8 minutes", url: "https://www.digitalpoint.com", description: "Sharing my complete roadmap for building a sustainable online income stream from zero: {LINK}", instructions: ["Create your free account", "Add your page link to your forum signature", "Participate in the Business & Marketing forums", "Share case studies and results", "Post consistently 3-5 times per week"] },
    { id: "mmo-5", name: "Quora Money Topics", niche: "Make Money Online", type: "Q&A", difficulty: "Easy", traffic: "800-3000 visitors/month", time: "10 minutes", url: "https://www.quora.com", description: "Free step-by-step guide to building a real online income from scratch — no experience needed: {LINK}", instructions: ["Set up your Quora profile with expertise in online income", "Search for 'how to make money online' questions", "Write detailed, credible answers with real examples", "Include your page URL as a helpful resource", "Answer 3-5 questions daily for maximum traffic"] },
    { id: "mmo-6", name: "IndieHackers Community", niche: "Make Money Online", type: "Social", difficulty: "Easy", traffic: "200-700 visitors/month", time: "8 minutes", url: "https://www.indiehackers.com", description: "Here's the exact system I used to go from zero to consistent online revenue as a solo founder: {LINK}", instructions: ["Create your IndieHackers profile", "Share your income journey or project", "Engage in group discussions about side income", "Link to your page in relevant conversations", "Post milestone updates to build credibility"] },
    { id: "mmo-7", name: "Medium Entrepreneurship", niche: "Make Money Online", type: "Blog", difficulty: "Medium", traffic: "500-2000 visitors/month", time: "15 minutes", url: "https://medium.com", description: "I broke down my entire process for building a profitable online business into this free guide: {LINK}", instructions: ["Write an article about your online income method", "Include your page URL as the primary resource", "Submit to publications like 'The Startup' or 'Better Marketing'", "Add relevant tags: 'Make Money', 'Side Hustle', 'Passive Income'", "Share your article on social media for extra reach"] },
    { id: "mmo-8", name: "r/Entrepreneur Reddit", niche: "Make Money Online", type: "Social", difficulty: "Easy", traffic: "500-1500 visitors/month", time: "5 minutes", url: "https://www.reddit.com/r/Entrepreneur", description: "This actionable guide covers everything you need to start making money online this week: {LINK}", instructions: ["Subscribe to r/Entrepreneur (2M+ members)", "Share a value-packed post about a real strategy", "Include your link naturally as a resource", "Engage in comments to boost post visibility", "Post during peak hours (8-10 AM EST) for best reach"] },
    { id: "mmo-9", name: "HackerNews", niche: "Make Money Online", type: "Social", difficulty: "Medium", traffic: "1000-5000 visitors/month", time: "5 minutes", url: "https://news.ycombinator.com", description: "Built a side income using this framework — sharing the full breakdown for anyone interested: {LINK}", instructions: ["Create a HackerNews account", "Submit interesting content related to online income", "Participate in Show HN discussions", "Add your link in relevant comment threads", "Focus on providing genuine value — this community hates spam"] },
    { id: "mmo-10", name: "Pinterest Business Pins", niche: "Make Money Online", type: "Social", difficulty: "Easy", traffic: "400-1500 visitors/month", time: "10 minutes", url: "https://www.pinterest.com", description: "Make Money Online Blueprint — Proven strategies for building passive income from home: {LINK}", instructions: ["Create business-focused boards: 'Side Hustle Ideas', 'Make Money From Home'", "Design eye-catching pins with income tips (use Canva)", "Link every pin to your page URL", "Use keywords in pin descriptions for SEO", "Pin 10-15 times per day for maximum reach"] },
    { id: "mmo-11", name: "Craigslist Services", niche: "Make Money Online", type: "Classified", difficulty: "Easy", traffic: "100-400 visitors/month", time: "5 minutes", url: "https://www.craigslist.org", description: "Free guide to earning extra income online — real, proven methods that actually work: {LINK}", instructions: ["Go to your local Craigslist", "Post in 'Services' or 'Gigs' section", "Write a compelling title mentioning earning potential", "Include your page URL in the post body", "Repost every 48 hours for continuous visibility"] },
    { id: "mmo-12", name: "Facebook Groups (MMO)", niche: "Make Money Online", type: "Social", difficulty: "Easy", traffic: "300-1000 visitors/month", time: "10 minutes", url: "https://www.facebook.com/groups", description: "This free training shows the simplest way to start generating income online from day one: {LINK}", instructions: ["Search Facebook for 'make money online' groups", "Join 10-15 active groups with 5K+ members", "Share value posts with your link", "Engage with other members' posts", "Post 2-3 times per week per group"] },

    // Health & Fitness
    { id: "hf-1", name: "Bodybuilding.com Forums", niche: "Health & Fitness", type: "Forum", difficulty: "Easy", traffic: "300-800 visitors/month", time: "10 minutes", url: "https://forum.bodybuilding.com", description: "Complete fitness guide with workout routines and nutrition tips to build your best physique: {LINK}", instructions: ["Create a free account at Bodybuilding.com", "Navigate to the supplement or fitness forums", "Share workout tips or supplement reviews", "Add your page URL to your forum signature", "Reply to 3-5 threads daily with helpful advice"] },
    { id: "hf-2", name: "r/Fitness Reddit", niche: "Health & Fitness", type: "Social", difficulty: "Easy", traffic: "500-2000 visitors/month", time: "5 minutes", url: "https://www.reddit.com/r/fitness", description: "Found this incredible free resource for building strength and improving overall fitness: {LINK}", instructions: ["Join r/fitness on Reddit (10M+ members)", "Share workout routines or fitness transformations", "Include your page as a supplementary resource", "Follow community rules strictly", "Engage in daily discussion threads"] },
    { id: "hf-3", name: "MyFitnessPal Forums", niche: "Health & Fitness", type: "Forum", difficulty: "Easy", traffic: "200-500 visitors/month", time: "8 minutes", url: "https://community.myfitnesspal.com", description: "This all-in-one fitness and nutrition guide made my training so much more effective: {LINK}", instructions: ["Log into MyFitnessPal community", "Browse fitness and exercise discussion boards", "Share your routine and results", "Include your page link in relevant posts", "Be consistent with weekly contributions"] },
    { id: "hf-4", name: "Quora Fitness Topics", niche: "Health & Fitness", type: "Q&A", difficulty: "Easy", traffic: "400-1500 visitors/month", time: "10 minutes", url: "https://www.quora.com", description: "Here's a free science-based fitness guide covering workouts, nutrition, and recovery strategies: {LINK}", instructions: ["Search for fitness and health questions on Quora", "Write detailed answers about workouts, supplements, and nutrition", "Link to your page as a helpful resource", "Include before/after results when possible", "Answer 2-3 questions daily"] },
    { id: "hf-5", name: "Fitocracy Community", niche: "Health & Fitness", type: "Social", difficulty: "Easy", traffic: "100-400 visitors/month", time: "8 minutes", url: "https://www.fitocracy.com", description: "Sharing this game-changing fitness resource that helped me level up my training results: {LINK}", instructions: ["Sign up for a free Fitocracy account", "Log workouts and engage with the community", "Join fitness groups and challenges", "Share your page link in your bio and relevant posts", "Help others with workout advice"] },
    { id: "hf-6", name: "T-Nation Forums", niche: "Health & Fitness", type: "Forum", difficulty: "Medium", traffic: "200-700 visitors/month", time: "10 minutes", url: "https://forums.t-nation.com", description: "Evidence-based training guide with programs for building real muscle and strength: {LINK}", instructions: ["Register at T-Nation forums", "Participate in training and nutrition discussions", "Share evidence-based advice and personal experiences", "Include your page URL in your signature", "This is a knowledgeable community — provide quality content"] },
    { id: "hf-7", name: "Pinterest Fitness Boards", niche: "Health & Fitness", type: "Social", difficulty: "Easy", traffic: "500-2000 visitors/month", time: "10 minutes", url: "https://www.pinterest.com", description: "Ultimate Fitness Guide — Expert workout plans and healthy nutrition tips for real results: {LINK}", instructions: ["Create boards: 'Home Workouts', 'Fitness Tips', 'Healthy Meals'", "Pin workout images and infographics", "Link each pin back to your page URL", "Use fitness-related keywords in descriptions", "Pin consistently — 5-10 pins per day"] },
    { id: "hf-8", name: "Medium Fitness Articles", niche: "Health & Fitness", type: "Blog", difficulty: "Medium", traffic: "300-1200 visitors/month", time: "15 minutes", url: "https://medium.com", description: "I put together a comprehensive guide to getting fit with practical, no-BS workout and diet advice: {LINK}", instructions: ["Write a helpful fitness article (500-800 words)", "Include your page URL as a resource", "Add tags: 'Fitness', 'Health', 'Workout', 'Wellness'", "Submit to fitness publications for more reach", "Publish 1-2 articles per week"] },

    // Tech & Gadgets
    { id: "tg-1", name: "Reddit r/gadgets", niche: "Tech & Gadgets", type: "Social", difficulty: "Easy", traffic: "500-2000 visitors/month", time: "5 minutes", url: "https://www.reddit.com/r/gadgets", description: "Just discovered this awesome tech guide with the best gadget picks and honest reviews: {LINK}", instructions: ["Join r/gadgets on Reddit", "Share genuine tech reviews or discoveries", "Include your link in relevant discussions", "Follow community posting rules", "Comment helpfully on other tech posts"] },
    { id: "tg-2", name: "Tom's Hardware Forums", niche: "Tech & Gadgets", type: "Forum", difficulty: "Easy", traffic: "200-600 visitors/month", time: "10 minutes", url: "https://forums.tomshardware.com", description: "This comprehensive tech buying guide saved me hours of research — covers all the top gadgets: {LINK}", instructions: ["Create your free forum account", "Help people with tech questions and recommendations", "Add your page URL to your forum signature", "Participate in buying guide discussions", "Post 3-5 helpful replies per week"] },
    { id: "tg-3", name: "Quora Tech Topics", niche: "Tech & Gadgets", type: "Q&A", difficulty: "Easy", traffic: "500-2000 visitors/month", time: "10 minutes", url: "https://www.quora.com", description: "Here's a curated guide to the best tech and gadgets right now with honest comparisons: {LINK}", instructions: ["Search for tech product questions on Quora", "Write detailed comparison and recommendation answers", "Include your page URL as a resource", "Focus on 'best gadget for...' type questions", "Answer 2-3 questions daily"] },
    { id: "tg-4", name: "SlickDeals Forums", niche: "Tech & Gadgets", type: "Forum", difficulty: "Easy", traffic: "300-1000 visitors/month", time: "8 minutes", url: "https://slickdeals.net/forums", description: "Found this amazing resource with top-rated tech deals and unbiased gadget reviews: {LINK}", instructions: ["Create a SlickDeals account", "Share deals and tech product reviews", "Include your link when discussing relevant products", "Participate in the Hot Deals forum", "Build reputation by sharing genuine value"] },
    { id: "tg-5", name: "Pinterest Tech Boards", niche: "Tech & Gadgets", type: "Social", difficulty: "Easy", traffic: "300-1200 visitors/month", time: "10 minutes", url: "https://www.pinterest.com", description: "Best Tech Gadgets Guide — Expert reviews and top picks for smart home, audio, and more: {LINK}", instructions: ["Create boards: 'Cool Gadgets', 'Tech Must-Haves', 'Smart Home'", "Pin product images with short reviews", "Link pins to your page URL", "Use tech keywords in descriptions", "Pin 5-10 times daily"] },
    { id: "tg-6", name: "Medium Tech Articles", niche: "Tech & Gadgets", type: "Blog", difficulty: "Medium", traffic: "400-1500 visitors/month", time: "15 minutes", url: "https://medium.com", description: "I reviewed the top gadgets worth buying right now and put everything in one easy guide: {LINK}", instructions: ["Write a gadget review or tech comparison article", "Include your page URL in the article", "Add tags: 'Technology', 'Gadgets', 'Reviews'", "Submit to tech publications on Medium", "Publish weekly for consistent traffic"] },

    // Beauty & Skincare
    { id: "bs-1", name: "MakeupAlley Forums", niche: "Beauty & Skincare", type: "Forum", difficulty: "Easy", traffic: "200-600 visitors/month", time: "10 minutes", url: "https://www.makeupalley.com", description: "This skincare routine guide transformed my skin — includes product recs for every skin type: {LINK}", instructions: ["Create a free MakeupAlley account", "Write product reviews and share your skincare routine", "Include your page link in relevant discussions", "Engage with other members' reviews", "Post consistently 3-5 times per week"] },
    { id: "bs-2", name: "Reddit r/SkincareAddiction", niche: "Beauty & Skincare", type: "Social", difficulty: "Easy", traffic: "500-2000 visitors/month", time: "5 minutes", url: "https://www.reddit.com/r/SkincareAddiction", description: "Free skincare guide with dermatologist-approved tips and affordable product recommendations: {LINK}", instructions: ["Join r/SkincareAddiction (2M+ members)", "Share your skincare routine or product reviews", "Include your link naturally in helpful posts", "Follow the strict community rules", "Engage in daily help threads"] },
    { id: "bs-3", name: "Quora Beauty Topics", niche: "Beauty & Skincare", type: "Q&A", difficulty: "Easy", traffic: "400-1500 visitors/month", time: "10 minutes", url: "https://www.quora.com", description: "Here's a complete beauty and skincare guide with routines that actually deliver visible results: {LINK}", instructions: ["Find beauty and skincare questions on Quora", "Write detailed answers about routines and products", "Include your page URL as a resource", "Focus on 'best product for...' questions", "Answer 2-3 questions daily"] },
    { id: "bs-4", name: "Pinterest Beauty Boards", niche: "Beauty & Skincare", type: "Social", difficulty: "Easy", traffic: "600-2500 visitors/month", time: "10 minutes", url: "https://www.pinterest.com", description: "Ultimate Skincare Guide — Expert tips, product picks, and routines for glowing, healthy skin: {LINK}", instructions: ["Create boards: 'Skincare Tips', 'Beauty Hacks', 'Anti-Aging'", "Pin skincare routine infographics and product images", "Link all pins to your page URL", "Use beauty-related keywords in descriptions", "Pin 10-15 times per day for maximum reach"] },
    { id: "bs-5", name: "EssentialDay Spa Forum", niche: "Beauty & Skincare", type: "Forum", difficulty: "Easy", traffic: "100-300 visitors/month", time: "8 minutes", url: "https://www.essentialdayspa.com/forum", description: "Sharing my go-to skincare resource with spa-quality tips you can easily do at home: {LINK}", instructions: ["Register for the forum", "Share skincare advice and product experiences", "Add your page URL to your signature", "Participate in skincare routine discussions", "Post weekly to stay visible"] },
    { id: "bs-6", name: "Medium Beauty Articles", niche: "Beauty & Skincare", type: "Blog", difficulty: "Medium", traffic: "300-1200 visitors/month", time: "15 minutes", url: "https://medium.com", description: "I compiled everything I've learned about skincare into this simple, results-driven beauty guide: {LINK}", instructions: ["Write a skincare tips or product review article", "Include your page URL naturally in the content", "Use tags: 'Beauty', 'Skincare', 'Self Care'", "Submit to beauty publications for more reach", "Publish 1-2 articles per week"] },

    // Relationships
    { id: "rel-1", name: "Reddit r/relationships", niche: "Relationships", type: "Social", difficulty: "Easy", traffic: "400-1500 visitors/month", time: "5 minutes", url: "https://www.reddit.com/r/relationships", description: "This relationship guide has genuinely helpful advice for building stronger, healthier connections: {LINK}", instructions: ["Join r/relationships on Reddit", "Offer genuinely helpful relationship advice", "Include your link when sharing relevant resources", "Be empathetic and follow community rules", "Engage with multiple posts daily"] },
    { id: "rel-2", name: "Quora Relationship Topics", niche: "Relationships", type: "Q&A", difficulty: "Easy", traffic: "600-2500 visitors/month", time: "10 minutes", url: "https://www.quora.com", description: "Here's a free guide with practical tips for improving communication and deepening your relationship: {LINK}", instructions: ["Search for relationship and dating questions", "Write thoughtful, detailed answers", "Include your page as a helpful resource", "Focus on 'how to improve relationship' questions", "Answer 2-3 questions daily"] },
    { id: "rel-3", name: "LoveShack Forum", niche: "Relationships", type: "Forum", difficulty: "Easy", traffic: "100-400 visitors/month", time: "8 minutes", url: "https://www.loveshack.org", description: "Found this amazing relationship resource full of expert advice on love, trust, and real connection: {LINK}", instructions: ["Create a free forum account", "Participate in relationship discussion threads", "Share helpful advice based on experience", "Add your page URL to your signature", "Post 3-5 times per week"] },
    { id: "rel-4", name: "Pinterest Relationship Boards", niche: "Relationships", type: "Social", difficulty: "Easy", traffic: "300-1200 visitors/month", time: "10 minutes", url: "https://www.pinterest.com", description: "Relationship Tips Guide — Strengthen your bond with these expert-backed communication strategies: {LINK}", instructions: ["Create boards: 'Relationship Tips', 'Date Ideas', 'Love Quotes'", "Pin relationship advice infographics", "Link pins to your page URL", "Use relationship keywords in descriptions", "Pin consistently every day"] },
    { id: "rel-5", name: "Talk About Marriage Forum", niche: "Relationships", type: "Forum", difficulty: "Easy", traffic: "150-500 visitors/month", time: "8 minutes", url: "https://www.talkaboutmarriage.com", description: "This guide to building a stronger marriage covers communication, trust, and keeping the spark alive: {LINK}", instructions: ["Register for the forum", "Offer supportive advice in discussion threads", "Share your page link in your forum signature", "Be genuine and empathetic in your responses", "Engage regularly with the community"] },
    { id: "rel-6", name: "Medium Relationship Articles", niche: "Relationships", type: "Blog", difficulty: "Medium", traffic: "400-1500 visitors/month", time: "15 minutes", url: "https://medium.com", description: "I wrote about the relationship habits that actually make a difference — based on research and experience: {LINK}", instructions: ["Write a relationship advice article (500-800 words)", "Include your page URL as a resource", "Add tags: 'Relationships', 'Love', 'Dating', 'Marriage'", "Submit to relationship publications", "Publish weekly for consistent traffic"] },

    // Pets
    { id: "pet-1", name: "DogForum Community", niche: "Pets", type: "Forum", difficulty: "Easy", traffic: "200-600 visitors/month", time: "10 minutes", url: "https://www.dogforum.com", description: "Complete dog care guide with training tips, health advice, and product recommendations from real owners: {LINK}", instructions: ["Create a free account", "Join dog training and health discussion threads", "Share helpful tips and personal experiences", "Add your page URL to your signature", "Post 3-5 times per week"] },
    { id: "pet-2", name: "Reddit r/dogs", niche: "Pets", type: "Social", difficulty: "Easy", traffic: "400-1500 visitors/month", time: "5 minutes", url: "https://www.reddit.com/r/dogs", description: "This free pet care resource has everything you need to keep your dog happy and healthy: {LINK}", instructions: ["Join r/dogs on Reddit (3M+ members)", "Share pet care tips and product recommendations", "Include your link naturally in helpful posts", "Follow community rules carefully", "Engage in daily discussion threads"] },
    { id: "pet-3", name: "TheCatSite Forum", niche: "Pets", type: "Forum", difficulty: "Easy", traffic: "150-500 visitors/month", time: "8 minutes", url: "https://thecatsite.com/forums", description: "Found this awesome guide for cat owners covering health, behavior, and the best products: {LINK}", instructions: ["Register at TheCatSite forums", "Participate in cat health and behavior discussions", "Share your expertise and product recommendations", "Include your page link in your signature", "Post consistently for visibility"] },
    { id: "pet-4", name: "Quora Pet Topics", niche: "Pets", type: "Q&A", difficulty: "Easy", traffic: "300-1200 visitors/month", time: "10 minutes", url: "https://www.quora.com", description: "Here's a comprehensive pet care guide with expert tips for keeping your furry friend thriving: {LINK}", instructions: ["Search for pet care questions on Quora", "Write detailed answers about pet health and products", "Include your page URL as a resource", "Focus on 'best product for dogs/cats' questions", "Answer 2-3 questions daily"] },
    { id: "pet-5", name: "Pinterest Pet Boards", niche: "Pets", type: "Social", difficulty: "Easy", traffic: "400-1500 visitors/month", time: "10 minutes", url: "https://www.pinterest.com", description: "Ultimate Pet Care Guide — Expert tips for dog and cat owners who want the best for their pets: {LINK}", instructions: ["Create boards: 'Dog Tips', 'Cat Care', 'Pet Products'", "Pin pet care infographics and product images", "Link all pins to your page URL", "Use pet-related keywords in descriptions", "Pin 5-10 times daily"] },
    { id: "pet-6", name: "PetForums.co.uk", niche: "Pets", type: "Forum", difficulty: "Easy", traffic: "100-400 visitors/month", time: "8 minutes", url: "https://www.petforums.co.uk", description: "Sharing this wonderful pet care resource packed with practical advice from experienced pet owners: {LINK}", instructions: ["Create a free account", "Join relevant pet discussion threads", "Share helpful advice about pet products and care", "Add your page link to your signature", "Be a genuine, active community member"] },

    // Home & Garden
    { id: "hg-1", name: "GardenWeb Forums", niche: "Home & Garden", type: "Forum", difficulty: "Easy", traffic: "200-600 visitors/month", time: "10 minutes", url: "https://www.houzz.com/discussions", description: "This home and garden guide is packed with DIY tips and project ideas that actually save money: {LINK}", instructions: ["Create a free Houzz account", "Browse the garden and home improvement forums", "Share DIY tips and product recommendations", "Include your page URL in relevant discussions", "Post consistently 3-5 times per week"] },
    { id: "hg-2", name: "Reddit r/HomeImprovement", niche: "Home & Garden", type: "Social", difficulty: "Easy", traffic: "400-1500 visitors/month", time: "5 minutes", url: "https://www.reddit.com/r/HomeImprovement", description: "Free guide with the best home improvement hacks and garden projects for every skill level: {LINK}", instructions: ["Join r/HomeImprovement (5M+ members)", "Share DIY tips, product reviews, or before/after projects", "Include your link naturally as a resource", "Follow community rules", "Engage with other posts daily"] },
    { id: "hg-3", name: "Quora Home Topics", niche: "Home & Garden", type: "Q&A", difficulty: "Easy", traffic: "300-1200 visitors/month", time: "10 minutes", url: "https://www.quora.com", description: "Here's a practical home improvement guide with step-by-step projects anyone can tackle: {LINK}", instructions: ["Search for home improvement and gardening questions", "Write detailed answers with practical advice", "Include your page URL as a resource", "Focus on 'how to' and 'best product for' questions", "Answer 2-3 questions daily"] },
    { id: "hg-4", name: "Pinterest Home & Garden", niche: "Home & Garden", type: "Social", difficulty: "Easy", traffic: "600-2500 visitors/month", time: "10 minutes", url: "https://www.pinterest.com", description: "Home & Garden Guide — Beautiful DIY projects and gardening tips to transform your space: {LINK}", instructions: ["Create boards: 'DIY Home', 'Garden Ideas', 'Home Hacks'", "Pin before/after images and DIY infographics", "Link all pins to your page URL", "Use home improvement keywords in descriptions", "Pin 10-15 times per day for maximum reach"] },
    { id: "hg-5", name: "DIY Chatroom Forum", niche: "Home & Garden", type: "Forum", difficulty: "Easy", traffic: "150-500 visitors/month", time: "8 minutes", url: "https://www.diychatroom.com", description: "Discovered this fantastic DIY resource with simple home projects that make a big impact: {LINK}", instructions: ["Register for the forum", "Browse home improvement discussion threads", "Share your DIY experiences and product recommendations", "Add your page URL to your signature", "Help others with their home projects"] },
    { id: "hg-6", name: "Medium Home Articles", niche: "Home & Garden", type: "Blog", difficulty: "Medium", traffic: "300-1200 visitors/month", time: "15 minutes", url: "https://medium.com", description: "I put together my best home improvement tips and garden hacks into one easy-to-follow guide: {LINK}", instructions: ["Write a home improvement tips or gardening article", "Include your page URL naturally in the content", "Add tags: 'Home', 'DIY', 'Garden', 'Home Improvement'", "Submit to relevant publications for more reach", "Publish 1-2 articles per week"] },];
